---
apiVersion: apps/v1
kind: Deployment                 
metadata:
  name: api-tester          
spec:
  replicas: 3                    
  selector:
    matchLabels:
      app: api-tester       
  template:                      
    metadata:
      labels:                    
        app: api-tester
    spec:                        
      containers:
      - name: api-tester
        image: norcinmo/api-tester:1.0.0 
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080  
        livenessProbe:           
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 15
          timeoutSeconds: 5
        readinessProbe:          
          httpGet:
            path: /readiness
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          timeoutSeconds: 1   