---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-tester
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-tester
  template:
    metadata:
      labels:
        app: api-tester
    spec:
      containers:
      - name: api-tester
        image: norcinmo/api-tester:1.0.1
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080